export const EXCLUDED_COMPANIES = [
    'Walt & Spencer',
    'Flipper',
    'Ufinity',
    'JH Partners',
    'Recruitment Sisters',
    'Sander',
    'Robert Walters',
    'Robert Half',
    'Michael Page',
    'Connescence',
    'Asteria HR Group',
    'Gentis',
    'Kingsley & Partners',
    'Dixon',
    'Generations Recruitment',
    'Alpen',
    'Abiomis',
    'Arbalett',
    'Wolfson',
    'Levy Global',
    'Le Grand & Associates',
    'Argateam',
    'Argafin',
    'Austin Bright',
    'Habeas',
    'Pensaert & Partners',
    'Financial Talents',
    'Konvert',
    'Linking Talents',
    'USG',
    'Cossel',
    'Pegasus',
    'Flowtech',
    'Hiring',
    'CTRL F',
    'Connect',
    'Bakker & Partners',
    'Elton Baker',
    'GBL Staffing Solutions',
    'ITZU',
    'Randstad',
    'Adecco',
    'Manpower',
    'FIXX Recruitment',
    'S&you Belgium',
    'Konvert',
    'Kingfisher',
    'Dixon',
    'Pragmist',
    'Unipartners',
    'Hays',
    'YER',
    'Hudson',
    'Mercuri Urval',
    'ACCA careers',
    'Talentus',
    'Azuro',
    'Airswift',
    'AEROCONTACT',
    'Broadgate',
]; 